/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlternatifRouteImport } from './routes/alternatif'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KriteriaRouteImport } from './routes/kriteria'
import { Route as PengaduanIndexRouteImport } from './routes/pengaduan.index'
import { Route as PengaduanIdRouteImport } from './routes/pengaduan.$id'
import { Route as PengaduanBaruRouteImport } from './routes/pengaduan.baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternatifRoute = AlternatifRouteImport.update({
  id: '/alternatif',
  path: '/alternatif',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KriteriaRoute = KriteriaRouteImport.update({
  id: '/kriteria',
  path: '/kriteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanIndexRoute = PengaduanIndexRouteImport.update({
  id: '/pengaduan/',
  path: '/pengaduan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanIdRoute = PengaduanIdRouteImport.update({
  id: '/pengaduan/$id',
  path: '/pengaduan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanBaruRoute = PengaduanBaruRouteImport.update({
  id: '/pengaduan/baru',
  path: '/pengaduan/baru',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternatif': typeof AlternatifRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/kriteria': typeof KriteriaRoute
  '/pengaduan/$id': typeof PengaduanIdRoute
  '/pengaduan/baru': typeof PengaduanBaruRoute
  '/pengaduan/': typeof PengaduanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternatif': typeof AlternatifRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/kriteria': typeof KriteriaRoute
  '/pengaduan/$id': typeof PengaduanIdRoute
  '/pengaduan/baru': typeof PengaduanBaruRoute
  '/pengaduan': typeof PengaduanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternatif': typeof AlternatifRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/kriteria': typeof KriteriaRoute
  '/pengaduan/$id': typeof PengaduanIdRoute
  '/pengaduan/baru': typeof PengaduanBaruRoute
  '/pengaduan/': typeof PengaduanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alternatif'
    | '/daftar'
    | '/dashboard'
    | '/kriteria'
    | '/pengaduan/$id'
    | '/pengaduan/baru'
    | '/pengaduan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alternatif'
    | '/daftar'
    | '/dashboard'
    | '/kriteria'
    | '/pengaduan/$id'
    | '/pengaduan/baru'
    | '/pengaduan'
  id:
    | '__root__'
    | '/'
    | '/alternatif'
    | '/daftar'
    | '/dashboard'
    | '/kriteria'
    | '/pengaduan/$id'
    | '/pengaduan/baru'
    | '/pengaduan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternatifRoute: typeof AlternatifRoute
  DaftarRoute: typeof DaftarRoute
  DashboardRoute: typeof DashboardRoute
  KriteriaRoute: typeof KriteriaRoute
  PengaduanIdRoute: typeof PengaduanIdRoute
  PengaduanBaruRoute: typeof PengaduanBaruRoute
  PengaduanIndexRoute: typeof PengaduanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatif': {
      id: '/alternatif'
      path: '/alternatif'
      fullPath: '/alternatif'
      preLoaderRoute: typeof AlternatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriteria': {
      id: '/kriteria'
      path: '/kriteria'
      fullPath: '/kriteria'
      preLoaderRoute: typeof KriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan/': {
      id: '/pengaduan/'
      path: '/pengaduan'
      fullPath: '/pengaduan/'
      preLoaderRoute: typeof PengaduanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan/$id': {
      id: '/pengaduan/$id'
      path: '/pengaduan/$id'
      fullPath: '/pengaduan/$id'
      preLoaderRoute: typeof PengaduanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan/baru': {
      id: '/pengaduan/baru'
      path: '/pengaduan/baru'
      fullPath: '/pengaduan/baru'
      preLoaderRoute: typeof PengaduanBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternatifRoute: AlternatifRoute,
  DaftarRoute: DaftarRoute,
  DashboardRoute: DashboardRoute,
  KriteriaRoute: KriteriaRoute,
  PengaduanIdRoute: PengaduanIdRoute,
  PengaduanBaruRoute: PengaduanBaruRoute,
  PengaduanIndexRoute: PengaduanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
